apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "db-admin"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "db-admin"  }}
    chart: {{ template "djangocms.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.postgres.enabled }}
  db-admin-password: {{ .Values.postgres.db.adminpwd | b64enc | quote }}
  {{ else }}
  db-admin-password: {{ .Values.database.adminpwd | b64enc | quote }}
  {{- end }}
