apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.fullName }}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ .Values.fullName }}
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90