apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "db"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "db"  }}
    chart: {{ template "djangocms.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.postgres.enabled }}
  {{- if .Values.postgres.db.password }}
  db-password: {{ .Values.postgres.db.password | b64enc | quote }}
  {{ else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{ else }}
  {{- if .Values.database.password }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  {{ else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}